cities:
  - name: Budapest
    locale: hu
    search_variants:
      - Budapest
      - "Budapest Hungary"
  - name: Debrecen
    locale: hu
    search_variants:
      - Debrecen
  - name: London
    locale: en
    search_variants:
      - London
      - "London UK"
