topics:
  - name: running
    search_terms:
      hu:
        - futás
        - futóklub
      en:
        - running
        - running club

  - name: board_games
    search_terms:
      hu:
        - társasjáték
        - társasjáték kör
      en:
        - board games
        - board game club

  - name: choir
    search_terms:
      hu:
        - kórus
        - énekkör
      en:
        - choir
        - singing group
